df <- read.csv('speedtest.csv', header=FALSE)
names(df) = c("datetime", "bytes_per_second")
library(dplyr)
speed <- mutate(df, mbits_per_second = bytes_per_second * 8 / 1000000)
library(ggplot2)
png("speedtest.png")
g <- ggplot(speed, aes(datetime, mbits_per_second))
g + geom_point()
dev.off()
